# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Pose.create(title: 'Bound Angle Pose', description:"Bound Angle Pose is a hip openning exercise to help counteract our chair accomodating hips.", difficulty:'Easy', videoId:'1', imageSrc:"https://www.yogajournal.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTQ2MjI3ODcyMDIwNTcxMTUz/yogapedia_272_10_fnl-forbladder.jpg")
Pose.create(title: 'Warrior Pose', description:">Warrior Pose is a core and leg strengthening pose. The legs are spread apart wider, and one heel is turned to face outward with the other heel facing forward. Next, the arms are extended outwards, parallel to the floor. Palms face downwards and the body leans towards the heel that faces outwards.", difficulty:'Easy', videoId:'2', imageSrc:"https://www.yogajournal.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTQ2MjI3ODcyMDE5ODUwODQ5/anatomy_287_3321_bjkforsacrum.jpg")
# Pose.create(title: 'Tree Pose', description:"This pose balances both the body and the mind. Advanced Tree Pose really builds awareness of one's centre of gravity and strengthens the entire body.", difficulty:'Intermediate', videoId:'5798000034', imageSrc:"https://www.yogajournal.com/.image/t_share/MTQ3MTU0OTQxNTE2MTk1NjMx/hp_291_1842_gn_bjk.jpg")
# Pose.create(title: 'Hero Pose', description:"Hero Pose is a relaxing pose in which one sits on their knees. It is a variation of Lotus Pose. The knees and hips are strengthened.", difficulty:'Advanced', videoId:'57987421111134', imageSrc:"https://www.yogajournal.com/.image/t_share/MTQ3MTU2OTEyOTA1OTIyMzUx/3yp_289_4609_bjk.jpg")
# Pose.create(title: 'Child Pose', description:"Child Pose is a relaxing pose that you can engage in after a strenous pose. All of the body's muscles including the facial muscles are relaxed.", difficulty:'Easy', videoId:'579834', imageSrc:"http://stylesatlife.com/wp-content/uploads/2015/10/balasana2.jpg")
# Pose.create(title: 'Lotus Pose', description:"Lotus Pose is a cross-legged position in which feet are placed on opposite thighs. Lotus Pose originates from meditative practices of ancient India.", difficulty:'Easy', videoId:'579834', imageSrc:"http://www.yoiup.com/wp-content/uploads/2017/04/pranayamayoga.com_.jpg")
# Pose.create(title: 'Boat Pose', description:"Boat Pose is performed by extending the legs outwards and sitting half-way up so that the upper body and thighs meet in a V-shape. Boat Pose strengthens the abs and hips.", difficulty:'Intermediate', videoId:'5798000034', imageSrc:"https://www.yogajournal.com/.image/t_share/MTQ3MTUyNzM1MjQ1MTgyNDE0/boathp_292_8_bjk.jpg")
Pose.create(title: 'One-Legged King Pigeon Pose', description:"One-Legged King Pigeon Pose is as interesting as its name. It is a pose that allows you to stretch your body and strengthen your back.", difficulty:'Advanced', videoId:'3', imageSrc:"https://www.yogajournal.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTQ2MjI3ODcyMDIwNjM3Mjgx/yp_290_1612_bjk-forhipflexors.jpg")
Pose.create(title: 'Cow Face Pose', description:"Cow Pose is a seated yoga pose.", difficulty:'Easy', videoId:'4', imageSrc:"https://www.yogajournal.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTQ2MjI3ODcyMDE5OTgxOTIx/cow-face-with-eagle-arms-forhips.jpg
")
